Repository julien040/anyquery, pull requests merged in 2025-09, with the labels that each got.

#59 ✨ Add carddav plugin
  plugins/carddav/.gitignore
  plugins/carddav/.goreleaser.yaml
  plugins/carddav/Makefile
  plugins/carddav/README.md
  plugins/carddav/address_book.go
  plugins/carddav/address_book_test.go
  plugins/carddav/carddav.go
  plugins/carddav/carddav_test.go
  plugins/carddav/contacts.go
  plugins/carddav/contacts_test.go
  plugins/carddav/go.mod
  plugins/carddav/go.sum
  plugins/carddav/main.go
  plugins/carddav/manifest.toml
  plugins/carddav/test.sh
Labels: enhancement

#57 fix(postgres): Handle case-sensitive column names
  module/postgres.go
Labels: bug

#58 MCP Trust Score
  README.md
Labels: documentation
